### ISSUE TITLE
Crash when opening camera on 7.0+ devices

### ISSUE THREAD

**Issue by crowelch** [miguelbcr/RxPaparazzo#34]
While running on 7.0+ and targeting API level 24

```Unable to start activity ComponentInfo{com.example.app/rx_activity_result.HolderActivity}: android.os.FileUriExposedException:file:///storage/emulated/0/Android/data/com.example.app/cache/shoot.jpg exposed beyond app through ClipData.Item.getUri()```

https://developer.android.com/reference/android/os/FileUriExposedException.html

**Comment by hemb** [comment]
Yes, same problem here. Temporary workaround is to set targetSdkVersion to 23.

**Comment by miguelbcr** [comment]
thanks to both of you!.
 I'll take a look this week

**Comment by miguelbcr** [comment]
Hi @crowelch and @hemb !
I've released [version 0.2.3](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.2.3).

Try it out and let me know if it works

**Comment by hemb** [comment]
Hi @miguelbcr!

Thank you for taking your time to look at it! The good news: I don't get the FileUriExposedException anymore. The bad: I still doesn't work

I'm using the following utility method. With Source.GALLERY I get a Response with RESULT_CANCELED after cropping the image and with Source.CAMERA it crashes before showing the camera UI. [trace.txt](https://github.com/miguelbcr/RxPaparazzo/files/453969/trace.txt).

`public static <A extends Activity> Observable<Response<A, String>> pickProfilePicImage(A activity, ImagePickerView.Source source) {
    Options options = new Options();
    options.setMaxResultSize(500, 500);

    Observable<Response<A, String>> obs;
    RxPaparazzo.BuilderImage<A> builder = RxPaparazzo.takeImage(activity).crop(options).useInternalStorage();
    if (source == ImagePickerView.Source.CAMERA) {
        obs = builder.usingCamera();
    } else {
        obs = builder.usingGallery();
    }

    return obs;
}`

**Comment by miguelbcr** [comment]
Hi @hemb!
Thanks , just I've got the same error when I've integrated it on my app. You can try [version 0.2.4](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.2.4) that solves that crash but I doesn't works properly, it doesn't close camera after accept the image, 

I'm trying to solve it ... sorry for the inconvenience

**Comment by miguelbcr** [comment]
Hi @hemb !
try [version 0.2.5](https://github.com/miguelbcr/RxPaparazzo/releases/tag/0.2.5) and let me know if it works...

Thanks

**Comment by hemb** [comment]
Yep, working fine now. Thanks again for a nice library!

**Comment by crowelch** [comment]
Works great, thanks for the fix!
